name: Build PlutoBook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.job }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libcairo2-dev \
          libexpat1-dev \
          libicu-dev \
          libfreetype6-dev \
          libfontconfig1-dev \
          libharfbuzz-dev \
          libcurl4-openssl-dev \
          libturbojpeg0-dev \
          libwebp-dev
          
    - name: Install Meson and Ninja
      run: |
        sudo apt-get install meson ninja-build
        
    - name: Setup and Build
      run: |
        meson setup build --wrap-mode=nodownload
        meson compile -C build

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        variant: sccache
        key: ${{ github.job }}
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install Meson and Ninja
      run: |
        pip3 install meson
        pip3 install ninja
        
    - name: Setup and Build
      run: |
        meson setup build
        meson compile -C build
